name: Test Simplified Workflow

on:
  push:
    branches:
      - feature/documentation-improvements
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test-detection:
    runs-on: ubuntu-latest
    outputs:
      test_output: ${{ steps.test.outputs.result }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Simple Detection Test
      id: test
      run: |
        echo "Testing detection logic"
        PROBLEMS_DETECTED=false
        
        # Simple test
        if [ -f "README.md" ]; then
          echo "README.md found"
        else
          PROBLEMS_DETECTED=true
        fi
        
        echo "result=$PROBLEMS_DETECTED" >> $GITHUB_OUTPUT
        echo "Detection complete: $PROBLEMS_DETECTED"
    
    - name: Test JavaScript Issues Creation
      if: steps.test.outputs.result == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          console.log('Testing issue creation logic');
          
          const issueTitle = 'Test Issue ' + new Date().toISOString();
          const issueBody = 'This is a test issue body';
          
          console.log('Title:', issueTitle);
          console.log('Body:', issueBody);
          
          // Just log what we would create
          console.log('Would create issue with:');
          console.log('- Title:', issueTitle);
          console.log('- Body:', issueBody);
          console.log('- Labels:', ['test', 'automated']);
          
          return { test: 'success' };