name: News Delivery System CI/CD

on:
  push:
    branches: [main, develop, feature/*, fix/*, release/*]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or ref to run CI on'
        required: false
        default: 'main'
  
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  issues: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Black formatter
        run: black --check .
        continue-on-error: true
      
      - name: Run Flake8 linter
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true
      
      - name: Run MyPy type checker
        run: mypy . --ignore-missing-imports
        continue-on-error: true

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: code-quality
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-asyncio
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run unit tests
        run: |
          pytest --cov=. --cov-report=xml --cov-report=html
        continue-on-error: true
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio httpx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run integration tests
        run: |
          if [ -d "tests/integration" ]; then
            pytest tests/integration/
          else
            echo "No integration tests found"
          fi
        continue-on-error: true

  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      
      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true
      
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [unit-tests, integration-tests]
    # Disabled: No production deployment needed for this project
    if: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Build project
        run: |
          echo "Building News Delivery System..."
          python -m compileall .
      
      - name: Prepare deployment directory
        run: |
          # Create a clean directory for deployment files
          mkdir -p deployment_files
          
          # Copy necessary files to deployment directory
          cp -r src deployment_files/
          cp -r config deployment_files/
          cp -r templates deployment_files/
          cp -r scripts deployment_files/
          cp requirements.txt deployment_files/ || true
          cp requirements-minimal.txt deployment_files/ || true
          cp README.md deployment_files/ || true
          cp CLAUDE.md deployment_files/ || true
          
          # Remove any __pycache__ directories that might have been copied
          find deployment_files -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find deployment_files -type f -name "*.pyc" -delete 2>/dev/null || true
      
      - name: Create deployment artifact
        run: |
          # Create archive from the prepared directory (outside of it to avoid recursion)
          tar -czf deployment.tar.gz -C deployment_files .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-${{ github.sha }}
          path: deployment.tar.gz
          retention-days: 7