name: Local CI Pipeline

# このワークフローはローカル実行やセルフホストランナー用に最適化されています
on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode'
        required: false
        type: boolean
        default: true

env:
  PYTHON_VERSION: '3.11'

jobs:
  # ========================================
  # ローカル実行用の軽量CI
  # ========================================
  local-ci:
    name: Local CI Check
    runs-on: self-hosted  # セルフホストランナーを使用
    # runs-on: ubuntu-latest  # GitHub ホストランナーを使用する場合
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run quick tests
        run: |
          # 統合テストのみ実行（高速）
          pytest tests/test_integration.py -v --tb=short
      
      - name: Check code quality
        continue-on-error: true
        run: |
          # Ruffがインストールされている場合のみ実行
          pip install ruff || true
          ruff check src/ tests/ --format=github || true
      
      - name: Summary
        if: always()
        run: |
          echo "## Local CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Python Version: ${{ env.PYTHON_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- Test Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Time: $(date)" >> $GITHUB_STEP_SUMMARY